### ISSUE TITLE
请问，DetectManager.Detect的参数三，我需要对回调的nv21做旋转处理吗？因为我这边一直识别不到人脸，

### ISSUE THREAD

**Issue by gxh-apologize** [C2H4-Tech/faceDetect#6]

**Comment by willims** [comment]
需要的，你要保证你的照片是正的

**Comment by gxh-apologize** [comment]
哦，明白了。谢谢回复，还有一个问题就是bbox.eyeDistance具体代表什么意思呢？

**Comment by willims** [comment]
相机预览的时候设置下旋转，
//相关参数代码，你可以参考一下代码
private int PREVIEW_WIDTH = 640;
private int PREVIEW_HEIGHT = 480;
nv21 = new byte[PREVIEW_WIDTH * PREVIEW_HEIGHT * 2];
parameters.setPreviewSize(PREVIEW_WIDTH, PREVIEW_HEIGHT);

bbox.eyeDistance已经废弃了，目前的Detect返回的就是两个眼睛中心点的距离d，这样根据d与PREVIEW_HEIGHT的比值判定人脸与相机的远近

**Comment by gxh-apologize** [comment]
请问您和以息科技是一家吗？他们的Demo用的就是您的库，里面bbox.eyeDistance/480来判断的，如果是的话我想问下大概多大距离拍照才能得到比较好的照片去侧皮肤。
我是在一个镜子上开发的，预览也是正的，拍照也是正的，现在就是回调的data不对，对data旋转后也不能识别人脸，我就保存成图片看了下，是花屏的，，，我再试试其他方法吧。

**Comment by willims** [comment]
这个你要自己去做实验分析的，人脸距离镜子中心点的距离多少合适，越远bbox.eyeDistance/480越小，反之越大，这个要你结合自己的使用场景做分析的哈
